services:
  db:
    image: postgres:13
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ".:/myapp"
      - uploads:/app/storage
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      SECRET_KEY_BASE: <secret-key-base-here>
      DATABASE_URL: postgres://postgres:password@db/myapp_development

volumes:
  postgres_data:
  uploads:
